### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by wstephan** [owagner/hm2mqtt#10]
Hi
I love to authenticate the hm2mqtt on my mosquitto running on raspberry pi in an other network. Great, if you can enhance this allready great piece of Software with this function.
Best regards
Steve

**Comment by owagner** [comment]
Implemented in v0.18

**Comment by wstephan** [comment]
Hi Oliver
vielen Dank für die rasche Implementierung meines Wunsches. Ich habe das Addon heruntergeladenen, aber irgendwie scheint der Build nicht zu funktionieren. Die Version ist immer noch 0.16.
Oder mache ich was falsch?
Herzliche Grüsse aus der Schweiz und schönen Sonntag
Stephan

**Comment by owagner** [comment]
Ich glaube, ich habe vergessen, die addon-Version zu erhöhen. Kannst Du bitte V0.18a probieren?

**Comment by owagner** [comment]
Hm, ich vermute, Du hättest das dann gerne auch in den addon-Settings? :)

**Comment by wstephan** [comment]
:-)
Ja, das wäre schön. Ich muss allerdings zu meiner Verteidigung sagen, dass ich den Code schon in meinem Eclipse ausgecheckt habe und mich nun einlese, wie man das selbst hinkriegt (und dann wäre ja dann ein Pull request angesagt, oder?). Aber ich bin leider noch nicht soweit: Github ist neu für mich, das builden von Java Projekten auch. 

Also, wenn Du das im Moment noch für mich erledigen kannst... wäre super!

Ich danke Dir und hoffe, ich kann Dir auch mal einen Stein in den Garten werfen (sagt man bei uns in der Schweiz so :-)
Lg
Stephan

**Comment by owagner** [comment]
Bitte mal mit v0.18b testen. Leider kann ich das addon selbst nicht testen.

**Comment by wstephan** [comment]
Hallo Oliver
ja, das funktioniert alles einwandfrei. Jetzt wo meine beide Homematics auf den Mosquitto Server verbinden können, merke ich, dass die Client Id diesselbe ist.. Kann man die über die Experteneinstellungen setzen? 

Herzliche Grüsse
Stephan

**Comment by owagner** [comment]
v0.18c...

**Comment by wstephan** [comment]
Hallo Oliver
kann man Dir irgendwo ne Kiste Bier vorbei bringen :-)
Danke funktioniert einwandfrei. Und melde Dich doch, wenn Du mal in der CH bist. Ich schulde Dir was!

Vielen Dank und einen schönen Sonntag noch!
Gruss
Stephan

P.S: Wenn Du gerne Kosmetik machst (ich nicht): Bei der Client ID ist das "(optional)" rausgefallen, es erscheint nur ")"

**Comment by owagner** [comment]
v0.18d
