### ISSUE TITLE
Kanaltyp publishen

### ISSUE THREAD

**Issue by hobbyquaker** [owagner/hm2mqtt#5]
Noch ein Feature Request :-)
ein Attribut hm_channeltype in den status Nachrichten

**Comment by owagner** [comment]
Ähm, DeviceDescription.TYPE oder was meinst du?

**Comment by hobbyquaker** [comment]
ich schließ das mal, weiss nicht mehr warum ich das haben wollte - kann also nicht wirklich wichtig gewesen sein :)
