### ISSUE TITLE
RPC via MQTT

### ISSUE THREAD

**Issue by hobbyquaker** [owagner/hm2mqtt#8]
Feature Wunsch - RPC via MQTT

z.B.:
`hm/command/rpc/<daemon>/getVersion/<cmd_id>`
und Antwort auf
`hm/response/rpc/<daemon>/getVersion/<cmd_id>`

Wobei `daemon` angibt ob man mit dem rfd oder dem hs485d sprechen möchte und die `cmd_id` einfach ein frei wählbarer Identifier ist den hm2mqtt bei der response wieder ins topic nimmt.

**Comment by owagner** [comment]
Das ist ein bischen schwieriger, wenn die Parameter des RPC-Calls komplizierter sind. Bei HMC gibt es dafür ja die strukturierte Textbeschreibung...
