### ISSUE TITLE
Kommst Du auch andere Werte der Objekte dran?

### ISSUE THREAD

**Issue by stefanbode** [owagner/hm2mqtt#9]
Hallo Oliver, 

erst mal super und genau das was ich gebraucht habe. Vor allem wegen der Integration in die Zentrale. Es gibt ein Projekt homegear welches von jemandem aus dem CCC gebaut wurde. Dieses liefert noch eine ganze Menge mehr Werte wie RSSI, Battrie Typ usw. 

Filterst Du oder ist das lles an Werten, was Du bekommen kannst? Homegear kann auch irgendwie MQTT aber Deine Lösung sagt mir im Moment mehr zu  :+1:

**Comment by owagner** [comment]
hm2mqtt filtert nichts, wenn Homegear diese Werte in den Paramsets listet und als Event schickt, wird hm2mqtt sie auch publishen
